apiVersion: apps/v1
kind: Deployment
metadata:
  name: manuscript
  labels:
    app: manuscript
    sidecar.istio.io/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manuscript
  template:
    metadata:
      labels:
        app: manuscript
    spec:
      containers:
        - name: manuscript
          image: "project10registry.azurecr.io/manuscript:latest"
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              value: 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
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
